allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - lucide-react@1.38.0
overrides:
  "@aws-sdk/credential-provider-node": 3.972.81
  deepmerge-ts: 8.0.2
  mysql2: 3.23.1
